# Generated by Django 5.0.4 on 2024-05-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expansion',
            name='expansion_img',
            field=models.ImageField(default='expansion_images/blank.jpg', upload_to='expansion_images/'),
        ),
    ]
