# Generated by Django 5.0.4 on 2024-05-25 18:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_card_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='owned_by_user',
        ),
        migrations.RemoveField(
            model_name='card',
            name='owner',
        ),
        migrations.AddField(
            model_name='card',
            name='owned_by_users',
            field=models.ManyToManyField(blank=True, related_name='owned_cards', to=settings.AUTH_USER_MODEL),
        ),
    ]
